# Generated by Django 2.0.6 on 2020-02-20 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=30, null=True)),
                ('author', models.CharField(blank=True, max_length=20, null=True)),
                ('publishing_house', models.CharField(blank=True, max_length=30, null=True)),
                ('publishing_time', models.DateField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=30, null=True)),
                ('print_time', models.DateField(blank=True, null=True)),
                ('print_count', models.BigIntegerField(blank=True, null=True)),
                ('comment_count', models.BigIntegerField(blank=True, null=True)),
                ('sale_count', models.BigIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=30, null=True)),
                ('char_count', models.BigIntegerField(blank=True, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('format_size', models.IntegerField(blank=True, null=True)),
                ('paper_type', models.CharField(blank=True, max_length=30, null=True)),
                ('wrap', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('d_price', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True)),
                ('editor_commend', models.TextField(blank=True, null=True)),
                ('content_intro', models.TextField(blank=True, null=True)),
                ('book_intro', models.TextField(blank=True, null=True)),
                ('author_intro', models.TextField(blank=True, null=True)),
                ('cataloh', models.TextField(blank=True, null=True)),
                ('media_comment', models.TextField(blank=True, null=True)),
                ('book_pic', models.CharField(blank=True, max_length=200, null=True)),
                ('content_all', models.TextField(blank=True, null=True)),
                ('book_cover', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TBookClass',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TOrderDetail',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_count', models.BigIntegerField(blank=True, null=True)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TBook')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TOrder')),
            ],
        ),
        migrations.CreateModel(
            name='TShoppingCardCon',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_count', models.BigIntegerField(blank=True, null=True)),
                ('book_id', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TBook')),
            ],
        ),
        migrations.CreateModel(
            name='TShoppingCart',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=30, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('user_password', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('token', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TUserAddress',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('detail_address', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('to_user', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('static_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TUser')),
            ],
        ),
        migrations.AddField(
            model_name='tshoppingcart',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TUser'),
        ),
        migrations.AddField(
            model_name='tshoppingcardcon',
            name='shopping_id',
            field=models.ForeignKey(db_column='shopping_id', on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TShoppingCart'),
        ),
        migrations.AddField(
            model_name='torder',
            name='user_id',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TUser'),
        ),
        migrations.AddField(
            model_name='tbook',
            name='book_class',
            field=models.ForeignKey(blank=True, db_column='book_class', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataapp.TBookClass'),
        ),
    ]
